# CI/CD
name: 02 CI Workflow

on:
  push:
    paths:
      - "app/**"
      - "tests/**"
      - "Dockerfile"
      - ".github/workflows/02-ci.yml"

  workflow_dispatch:

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run Ruff
        run: ruff check .

      - name: Run Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          scan-type: fs
          scan-ref: .
          format: table
          output: trivy-fs-report.txt
          exit-code: 1
          severity: CRITICAL,HIGH

      - name: Run Trivy Dockerfile Scan
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          scan-type: config
          scan-ref: Dockerfile
          format: table
          output: trivy-dockerfile-report.txt
          exit-code: 1
          severity: CRITICAL

      - name: Upload Trivy Scan Artifact
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: trivy-scan-artifact-python-${{ matrix.python-version }}
          path: |
            trivy-fs-report.txt
            trivy-dockerfile-report.txt

      - name: Check current time
        run: date

      - name: Run tests
        run: python -m unittest discover -s tests -v

  build-artifact:
    name: Build Docker Artifact
    runs-on: ubuntu-latest
    needs: run-tests

    env:
      IMAGE_NAME: tiny-health-app
      IMAGE_TAR: tiny-health-app.tar
      IMAGE_METADATA: image-metadata.env
      ARTIFACT_NAME: tiny-health-app-image

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set image tag
        id: image-tag
        run: |
          TODAY="$(date -u +%Y-%m-%d)"
          IMAGE_TAG="${TODAY}-${GITHUB_RUN_ID}"
          echo "image_tag=$IMAGE_TAG" >> "$GITHUB_OUTPUT"

      - name: Build Docker image
        run: |
          docker build \
            -t "${IMAGE_NAME}:${{ steps.image-tag.outputs.image_tag }}" \
            .

      - name: Run Trivy Image Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: "${{ env.IMAGE_NAME }}:${{ steps.image-tag.outputs.image_tag }}"
          format: table
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "HIGH,CRITICAL"
          

      - name: Save Docker image as artifact file
        run: docker save "${IMAGE_NAME}:${{ steps.image-tag.outputs.image_tag }}" -o "${IMAGE_TAR}"


      - name: Save image metadata
        run: |
          IMAGE_REFERENCE="${IMAGE_NAME}:${{ steps.image-tag.outputs.image_tag }}"
          printf 'IMAGE_TAG=%s\n' "${{ steps.image-tag.outputs.image_tag }}" > "${IMAGE_METADATA}"
          printf 'IMAGE_REFERENCE=%s\n' "${IMAGE_REFERENCE}" >> "${IMAGE_METADATA}"

      - name: Upload build artifact
        uses: actions/upload-artifact@v5
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: |
            ${{ env.IMAGE_TAR }}
            ${{ env.IMAGE_METADATA }}
          retention-days: 7